sabzweb/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'), #example route
    path('posts/', views.posts, name='posts'),
    path('posts/<int:id>/', views.post, name='post_detail'),
]

sabzweb/sabzweb/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls'))
]

sabzweb/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

#managers
class PublishedManager(models.Manager):
    def get_queryset(self):
       return super().get_queryset().filter(status=Post.Status.PUBLISHED)

# Create your models here.
class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DR', 'Draft'
        PUBLISHED = 'PB','Published'
        REJECTED = 'RJ','Rejected'
    #relations
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_posts')
    # data fields
    title = models.CharField(max_length=250)
    description = models.TextField()
    slug = models.SlugField(max_length=250)

    #date
    published = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    #choises fields
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)

    objects = models.Manager() #default manager
    published_posts = PublishedManager() #custom manager

    class Meta:
        ordering = ['-published']
        indexes = [
            models.Index(fields=['published'])
        ]

    def __str__(self):
        return self.title

sabzweb/blog/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.shortcuts import get_object_or_404
from . models import Post

# Create your views here.

def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")

def posts(request):
    post_list = Post.published_posts.all()
    context = {
        'posts': post_list
    }
    return render(request, 'blog/list.html', context)

def post(request, id):
    detail = get_object_or_404(Post, id=id, status= Post.Status.PUBLISHED)
   # try:
   #     detail = Post.published_posts.get(id=id)
   # except:
   #     raise Http404

    context = {
        'post': detail
    }
    return render(request, 'blog/detail.html',context)

sabzweb/blog/templates/blog/detail.html
{% extends 'parent/base.html'%}
{% block title %}post detail {% endblock %}

{% block content %}
    <h1>post detail</h1>
    <h2>{{ post.title }} (by {{ post.author }})</h2>
    <p>{{ post.description|linebreaks }}</p>
    <hr>
{% endblock %}

sabzweb/blog/templates/blog/list.html
{% extends 'parent/base.html' %}
{% block title %} post list {% endblock %}
{% block content %}
    <h1>post list</h1>

    {% for post in posts %}
        <h2>
            <a href="{% url 'blog:post_detail' post.id %}" >{{ post.title }}</a>
        </h2>
        <p>{{ post.description|truncatewords:4}}</p>
    {% endfor %}
{% endblock %}

sabzweb/blog/templates/parent/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" type="text/css" href=" {% static 'css/base.css' %}">
    {% block head %} {% endblock %}
</head>
<body>
{% include 'partials/header.html' %}
{% include 'partials/navigation.html' %}
{% block content %}{% endblock %}
{% include 'partials/footer.html' %}
</body>
</html>

sabzweb/blog/templates/partials/footer.html
<p>footer</p>

sabzweb/blog/templates/partials/header.html
<p>header</p>

sabzweb/blog/templates/partials/navigation.html
<p> navigation </p>